Improvements to Test Templates
Dhii/bootstrap pull request #16
Opened 2017-08-27 11:29 UTC by mecha

2017-08-27 20:55 UTC, XedinUnknown requested changes
What if we also add a `use {{ns}}\MyClass as TestSubject`, and then typehint `TestSubject` instead of the FQN?

2017-08-27 20:55 UTC, XedinUnknown commented on test/unit/MyClassUnitTest.php
> +    const TEST_SUBJECT_CLASSNAME = '{{quote_ns}}\\MyClass';
Escaping of the backslash is no longer required.

2017-08-30 10:12 UTC, mecha commented
@XedinUnknown I like the idea! Added the alias for `TestSubject`.

2017-09-10 15:06 UTC, XedinUnknown requested changes

2017-09-10 15:06 UTC, XedinUnknown commented on test/functional/MyClassFuncTest.php
> +class MyClassFuncTest extends TestCase
Unnecessary, as it's already in the `FuncTest` namespace. Also, does not follow the general pattern; see `use` above.

2017-09-10 15:06 UTC, XedinUnknown commented on test/unit/MyClassUnitTest.php
>  namespace {{ns}}\FuncTest;
Last segment of namespace should be `UnitTest`

2017-09-10 15:06 UTC, XedinUnknown commented on test/unit/MyClassUnitTest.php
> +class MyClassUnitTest extends TestCase
Again, probably does not need `UnitTest` because the namespace is sufficient.

2017-09-10 15:06 UTC, XedinUnknown commented on test/unit/MyClassUnitTest.php
>   * Tests {@see {{ns}}\MyClass}.
Again, should probably reference `TestSubject` instead.

2017-09-15 15:13 UTC, XedinUnknown approved these changes

2017-09-15 15:13 UTC, merged